<!DOCTYPE html>
<!--[if IE 6]>
<html id="ie6" lang="en-US">
<![endif]-->
<!--[if IE 8]>
<html id="ie8" lang="en-US">
<![endif]-->
<!--[if (!IE)]><!-->
<html lang="en-US">
<!--<![endif]-->

<head>
<meta charset="UTF-8" />
<title>Page not found | Noctua</title>
<link rel="profile" href="http://gmpg.org/xfn/11" />
<link rel="pingback" href="http://blog-noctua.rhcloud.com/xmlrpc.php" />
<link rel="alternate" type="application/rss+xml" title="Noctua &raquo; Feed" href="http://blog-noctua.rhcloud.com/index.php/feed/" />
<link rel="alternate" type="application/rss+xml" title="Noctua &raquo; Comments Feed" href="http://blog-noctua.rhcloud.com/index.php/comments/feed/" />
<link rel='stylesheet' id='coraline-css'  href='http://blog-noctua.rhcloud.com/wp-content/themes/coraline/style.css?ver=4.1.10' type='text/css' media='all' />
<script type='text/javascript' src='http://blog-noctua.rhcloud.com/wp-content/jw-player-plugin-for-wordpress/player/jwplayer.js?ver=4.1.10'></script>
<script type='text/javascript' src='http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js?ver=4.1.10'></script>
<script type='text/javascript' src='http://blog-noctua.rhcloud.com/wp-includes/js/swfobject.js?ver=2.2-20120417'></script>
<script type='text/javascript' src='http://blog-noctua.rhcloud.com/wp-content/plugins/wp-d3/js/d3.3.5.5.min.js?ver=1.0.0'></script>
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://blog-noctua.rhcloud.com/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://blog-noctua.rhcloud.com/wp-includes/wlwmanifest.xml" /> 
<meta name="generator" content="WordPress 4.1.10" />

<!-- Start Of Script Generated By cforms v8.7 [Oliver Seidel | www.deliciousdays.com] -->
<link rel="stylesheet" type="text/css" href="http://blog-noctua.rhcloud.com/wp-content/plugins/cforms/styling/cforms.css" />
<script type="text/javascript" src="http://blog-noctua.rhcloud.com/wp-content/plugins/cforms/js/cforms.js"></script>
<!-- End Of Script Generated By cforms -->

	<link href="http://blog-noctua.rhcloud.com/wp-content/plugins/google-syntax-highlighter/Styles/SyntaxHighlighter.css" type="text/css" rel="stylesheet" />
	<!-- Vipers Video Quicktags v6.3.0 | http://www.viper007bond.com/wordpress-plugins/vipers-video-quicktags/ -->
<style type="text/css">
.vvqbox { display: block; max-width: 100%; visibility: visible !important; margin: 10px auto; } .vvqbox img { max-width: 100%; height: 100%; } .vvqbox object { max-width: 100%; } 
</style>
<script type="text/javascript">
// <![CDATA[
	var vvqflashvars = {};
	var vvqparams = { wmode: "opaque", allowfullscreen: "true", allowscriptaccess: "always" };
	var vvqattributes = {};
	var vvqexpressinstall = "http://blog-noctua.rhcloud.com/wp-content/plugins/vipers-video-quicktags/resources/expressinstall.swf";
// ]]>
</script>
</head>

<body class="error404 two-column content-sidebar">
<div id="container" class="hfeed contain">
	<div id="header">
		<div id="masthead" role="banner">
						<div id="site-title">
				<span>
					<a href="http://blog-noctua.rhcloud.com/" title="Noctua" rel="home">Noctua</a>
				</span>
			</div>
			<div id="site-description">CG Tools</div>
		</div><!-- #masthead -->

		<div id="access" role="navigation">
		  			<div class="skip-link screen-reader-text"><a href="#content" title="Skip to content">Skip to content</a></div>
						<div class="menu"><ul><li ><a href="http://blog-noctua.rhcloud.com/">Home</a></li><li class="page_item page-item-2"><a href="http://blog-noctua.rhcloud.com/index.php/about/">About</a></li><li class="page_item page-item-92"><a href="http://blog-noctua.rhcloud.com/index.php/contact/">Contact</a></li><li class="page_item page-item-341"><a href="http://blog-noctua.rhcloud.com/index.php/resume/">Resume</a></li></ul></div>
		</div><!-- #access -->

		<div id="branding">
						<a href="http://blog-noctua.rhcloud.com/">
									<img src="http://blog-noctua.rhcloud.com/wp-content/header_41.jpg" width="770" height="140" alt="" />
							</a>
					</div><!-- #branding -->
	</div><!-- #header -->

	<div id="content-box">

<div id="content-container">
	<div id="content" role="main">

		<div id="post-0" class="post error404 not-found">
			<h1 class="entry-title">Not Found</h1>
			<div class="entry-content">
				<p>Apologies, but the page you requested could not be found. Perhaps searching will help.</p>
				<form role="search" method="get" id="searchform" class="searchform" action="http://blog-noctua.rhcloud.com/">
				<div>
					<label class="screen-reader-text" for="s">Search for:</label>
					<input type="text" value="" name="s" id="s" />
					<input type="submit" id="searchsubmit" value="Search" />
				</div>
			</form>			</div><!-- .entry-content -->
		</div><!-- #post-0 -->

	</div><!-- #content -->
</div><!-- #content-container -->

	</div><!-- #content-box -->

	<div id="footer" role="contentinfo">
		
		<div id="colophon">
			<span class="generator-link"><a href="http://wordpress.org/" title="A Semantic Personal Publishing Platform" rel="generator">Proudly powered by WordPress.</a></span>
			Theme: Coraline by <a href="https://wordpress.com/themes/" rel="designer">WordPress.com</a>.		</div><!-- #colophon -->
	</div><!-- #footer -->

</div><!-- #container -->

<script class="javascript" src="http://blog-noctua.rhcloud.com/wp-content/plugins/google-syntax-highlighter/Scripts/shCore.js"></script>
<script class="javascript" src="http://blog-noctua.rhcloud.com/wp-content/plugins/google-syntax-highlighter/Scripts/shBrushCSharp.js"></script>
<script class="javascript" src="http://blog-noctua.rhcloud.com/wp-content/plugins/google-syntax-highlighter/Scripts/shBrushPhp.js"></script>
<script class="javascript" src="http://blog-noctua.rhcloud.com/wp-content/plugins/google-syntax-highlighter/Scripts/shBrushJScript.js"></script>
<script class="javascript" src="http://blog-noctua.rhcloud.com/wp-content/plugins/google-syntax-highlighter/Scripts/shBrushJava.js"></script>
<script class="javascript" src="http://blog-noctua.rhcloud.com/wp-content/plugins/google-syntax-highlighter/Scripts/shBrushVb.js"></script>
<script class="javascript" src="http://blog-noctua.rhcloud.com/wp-content/plugins/google-syntax-highlighter/Scripts/shBrushSql.js"></script>
<script class="javascript" src="http://blog-noctua.rhcloud.com/wp-content/plugins/google-syntax-highlighter/Scripts/shBrushXml.js"></script>
<script class="javascript" src="http://blog-noctua.rhcloud.com/wp-content/plugins/google-syntax-highlighter/Scripts/shBrushDelphi.js"></script>
<script class="javascript" src="http://blog-noctua.rhcloud.com/wp-content/plugins/google-syntax-highlighter/Scripts/shBrushPython.js"></script>
<script class="javascript" src="http://blog-noctua.rhcloud.com/wp-content/plugins/google-syntax-highlighter/Scripts/shBrushRuby.js"></script>
<script class="javascript" src="http://blog-noctua.rhcloud.com/wp-content/plugins/google-syntax-highlighter/Scripts/shBrushCss.js"></script>
<script class="javascript" src="http://blog-noctua.rhcloud.com/wp-content/plugins/google-syntax-highlighter/Scripts/shBrushCpp.js"></script>
<script class="javascript">
dp.SyntaxHighlighter.ClipboardSwf = 'http://blog-noctua.rhcloud.com/wp-content/plugins/google-syntax-highlighter/Scripts/clipboard.swf';
dp.SyntaxHighlighter.HighlightAll('code');
</script>
</body>
</html>